#
# Purpose: Deploy app to GitHub Pages
#

name: deploy

on:
  # Run workflow manually
  workflow_dispatch:
  
  # pushes to specific branches
  push:
    branches: [main]

# Allow only one concurrent deployment
concurrency:
  group: deploy
  cancel-in-progress: false

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

defaults:
  run:
    shell: bash
    working-directory: ./src

jobs:
    test:
      uses: sbartholomeusz/gh-actions-common/.github/workflows/npm-test.yml@v1
      with:
        node_version: '16'
        path: './src'
        os_platform: 'ubuntu-latest'

    build:
      needs: [test]
      runs-on: ubuntu-latest
      steps:
       - name: 'Check out source code'
         uses: actions/checkout@v4

       - name: 'Setup GH Pages'
         uses: actions/configure-pages@v3
      
       - name: 'Install node'
         uses: actions/setup-node@v3
         with:
          node-version: 16

       - name: 'Fetch dependencies'
         run: npm ci

       - name: 'Build'
         run: npm run build-gh-pages

       - name: Upload build artifact
         uses: actions/upload-pages-artifact@v2
         with:
           path: ./src/dist/cinnamon

    deploy:
      needs: [build]
      runs-on: ubuntu-latest
      # Deploy to the github-pages environment
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
      steps:
        - name: Deploy to build to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v2